name: cloudcannon configure validate --configuration [valid]

steps:
  - step: I have a "cloudcannon.config.yml" file with the content {yaml}
    yaml: |-
      collections_config:
        posts:
          path: _posts
  - ref: ../../core/run-cli.toolproof.yml
  - step: I run {command}
    command: |
      npm -s run cloudcannon -- configure validate . --configuration | sed 's|/.*/||'
  - snapshot: stdout
    snapshot_content: |-
      ╎✓ valid: cloudcannon.config.yml
