name: CLI init-settings subcommand

steps:
  - I run "cp -R %test_sites%/sendit-astro-template src"
  - ref: ../core/run-cli.toolproof.yml
  - I run "npm -s run cloudcannon -- configure init-settings src"
  - I run "cat src/.cloudcannon/initial-site-settings.json"
  - stdout should contain "astro"
  - stdout should contain "install_command"
  - stdout should contain "build_command"
  - stdout should contain "output_path"
