name: cloudcannon validate [valid, no settings file]

steps:
  - step: I have a "cloudcannon.config.yml" file with the content {yaml}
    yaml: |-
      collections_config:
        posts:
          path: _posts
  - ref: ../core/run-cli.toolproof.yml
  - step: I run {command}
    command: |
      npm -s run cloudcannon -- validate . 2>&1 || true
  - snapshot: stdout
    snapshot_content: |-
      ╎✓ valid: cloudcannon.config.yml
      ╎✓ valid: editor links (none found)
