name: cloudcannon validate --configuration [invalid, with split files]

steps:
  - step: I have a "cloudcannon.config.yml" file with the content {yaml}
    yaml: |-
      something: this does not belong here
      collections_config_from_glob:
        - cloudcannon.collections.yml
        - custom-colls.yml
      _editables_from_glob:
        - cloudcannon.editables.yml
      _inputs_from_glob:
        - cloudcannon.inputs.yml
        - cloudcannon.inputs.json
        - blog.cloudcannon.inputs.yml
      _snippets_from_glob:
        - cloudcannon.snippets.yml
      _snippets_definitions_from_glob:
        - cloudcannon.snippets-definitions.yml
      _snippets_imports_from_glob:
        - cloudcannon.snippets-imports.yml
      _structures_from_glob:
        - cloudcannon.structures.yml
  - step: I have a "cloudcannon.inputs.yml" file with the content {yaml}
    yaml: |-
      date:
        type: datetime
        instance_value: now
  - step: I have a "blog.cloudcannon.inputs.yml" file with the content {yaml}
    yaml: |-
      date:
        type: datetime
        instance_value: now
  - step: I have a "cloudcannon.structures.yml" file with the content {yaml}
    yaml: |-
      article:
        reorder_inputs: not-a-boolean
        values_from_glob:
          - cloudcannon.structure-value.yml
  - step: I have a "cloudcannon.structure-value.yml" file with the content {yaml}
    yaml: |-
      label: missing-required-value
  - step: I have a "cloudcannon.collections.yml" file with the content {yaml}
    yaml: |-
      posts:
        sort: 123
        schemas_from_glob:
          - cloudcannon.schemas.yml
  - step: I have a "custom-colls.yml" file with the content {yaml}
    yaml: |-
      staff:
        path: staff-members
        sort_options:
          - hello
  - step: I have a "cloudcannon.schemas.yml" file with the content {yaml}
    yaml: |-
      article:
        reorder_inputs: not-a-boolean
  - step: I have a "cloudcannon.editables.yml" file with the content {yaml}
    yaml: |-
      content:
        bold: not-a-boolean
  - step: I have a "cloudcannon.snippets.yml" file with the content {yaml}
    yaml: |-
      callout:
        template: 123
  - step: I have a "cloudcannon.snippets-definitions.yml" file with the content {yaml}
    yaml: |-
      callout: 123
  - step: I have a "cloudcannon.inputs.json" file with the content {json}
    json: |-
      {
        "date": { "type": "datetime", "instance_value": "now" }
      }
  - step: I have a "cloudcannon.snippets-imports.yml" file with the content {yaml}
    yaml: |-
      mdx:
        path: 123
  - ref: ../core/run-cli.toolproof.yml
  - step: I run {command}
    command: |
      npm -s run cloudcannon -- validate . --configuration 2>&1 || true
  - snapshot: stdout
    snapshot_content: |-
      ╎✗ invalid: cloudcannon.config.yml
      ╎  $: unexpected property something
      ╎✗ invalid: cloudcannon.snippets.yml
      ╎  $.callout.template: unexpected type number, allowed types: string
      ╎✗ invalid: cloudcannon.snippets-imports.yml
      ╎  $.mdx: unexpected type object, allowed types: boolean
      ╎  $.mdx: must have required property exclude
      ╎  $.mdx: must have required property include
      ╎✓ valid: cloudcannon.snippets-definitions.yml
      ╎✗ invalid: cloudcannon.collections.yml
      ╎  $.posts: must have required property path
      ╎  $.posts: unexpected property sort
      ╎✗ invalid: custom-colls.yml
      ╎  $.staff.sort_options[0]: unexpected type string, allowed types: object
      ╎✗ invalid: blog.cloudcannon.inputs.yml
      ╎  $.date.instance_value: unexpected value now, allowed values: UUID, NOW
      ╎✗ invalid: cloudcannon.inputs.json
      ╎  $.date.instance_value: unexpected value now, allowed values: UUID, NOW
      ╎✗ invalid: cloudcannon.inputs.yml
      ╎  $.date.instance_value: unexpected value now, allowed values: UUID, NOW
      ╎✗ invalid: cloudcannon.editables.yml
      ╎  $.content.bold: unexpected type string, allowed types: boolean
      ╎✗ invalid: cloudcannon.structures.yml
      ╎  $.article.reorder_inputs: unexpected type string, allowed types: boolean
      ╎✗ invalid: cloudcannon.structure-value.yml
      ╎  $: must have required property value
      ╎✗ invalid: cloudcannon.schemas.yml
      ╎  $.article: must have required property path
      ╎  $.article.reorder_inputs: unexpected type string, allowed types: boolean
